### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by TBD** [TBD/lbsim#1]
comment here or via twitter with your feature requests

v1.0.0 - release 2015.Dec
- [ ] web based editor (add/move/delete modules)
- [ ] URL based circuit save (base64 compressed) - easy to share without making an account
- [ ] basic modules:
  - [ ] power
  - [ ] button
  - [ ] led
  - [ ] oscillator
- [ ] sidebar with basic info, wikipedia links, basic tutorials
- [ ] module library:
  - [ ] realtime search with module preview
  - [ ] drag/drop to canvas
- [ ] keyboard shortcuts
  - [ ] selection ←↑↓→
  - [ ] copy/cut/paste modules
  - [ ] search library
  - [ ] power on/off circuit
